2022/8/4 14:09:45 System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 14:12:03 System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 14:27:50 System.Net.WebException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:192.168.80.3]:8080 (192.168.80.3:8080)
 ---> System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:192.168.80.3]:8080 (192.168.80.3:8080)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:192.168.80.3]:8080
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 16:33:07 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 16:35:40 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 16:36:17 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 16:36:46 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 16:37:17 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 16:37:48 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 16:39:48 System.Net.WebException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:192.168.80.3]:8080 (192.168.80.3:8080)
 ---> System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:192.168.80.3]:8080 (192.168.80.3:8080)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:192.168.80.3]:8080
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 16:46:07 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 16:46:22 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 16:48:40 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 17:10:04 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 17:27:46 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 17:27:46 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 17:39:02 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 18:28:53 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 18:29:03 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 18:30:16 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 18:35:01 System.Net.WebException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:192.168.80.3]:8080 (192.168.80.3:8080)
 ---> System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:192.168.80.3]:8080 (192.168.80.3:8080)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 [::ffff:192.168.80.3]:8080
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 19:52:39 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
2022/8/4 20:23:22 System.Net.WebException: The remote server returned an error: (400) .
   at System.Net.HttpWebRequest.GetResponse()
   at Testdemo.Class.HTTP.HttpPost(String Url, String postDataStr) in E:\Code\Testdemo\Testdemo\Class\HTTP.cs:line 30
